const { reactionEmojis } = require('../../Library/emoji');

module.exports.execute = async (client, flag, arg, M) => {
    const greetings = [
        'Hello there!',
        'Hey!',
        'Hi!',
        'Hola!',
        'Namaste!',
        'Salam!',
        'Bonjour!',
        'Wassup!',
        'Sup!',
        'Wassap!',
        'Hey, how are you?',
        'Hi, how are you?',
        'Hello, how are you?',
        'Howdy!',
        'Greetings!',
        'Good day!',
        'What’s up?',
        'Yo!',
        'How’s it going?',
        'Hey, what’s new?',
        'Howdy, partner!',
        'Hi there!',
        'Hey, how’s everything?',
        'Hey, how’s life?',
        'Hello, friend!',
        'What’s happening?',
        'How are things?',
        'Hiya!',
        'Hey, how’s your day?',
        'Hello, mate!',
        'How are you doing?',
        'How’s everything?',
        'Hi, good to see you!',
        'What’s good?',
        'Hey, how’s it hanging?',
        'Hi, how have you been?',
        'What’s the news?',
        'How’s life treating you?',
        'Hey, what’s going on?',
        'How’s your day?',
        'Hey, how have you been?',
        'Hello, how have you been?',
        'Good to see you!',
        'Hey, long time no see!',
        'Hi, long time no see!',
        'How’s your day been?',
        'Hey, what’s up?',
        'How have you been?',
        'Hey, what have you been up to?',
        'How’s everything going?',
        'Hey, what’s happening?',
        'Hi, what’s new?',
        'What’s going on?',
        'How’s your life?',
        'Hey, how’s your day going?',
        'How’s your day been so far?',
        'Hey, what’s new with you?',
        'Hi, what have you been doing?',
        'How’s life been treating you?',
        'How’s everything been?',
        'How have you been doing?',
        'Hey, what have you been doing?',
        'How’s your world?',
        'What’s new with you?',
        'What’s the latest?',
        'Hey, what’s the word?',
        'How have you been lately?',
        'How’s life been?',
        'Hey, what’s been up?',
        'How’s everything with you?',
        'What’s new with you?',
        'Hey, how’s your week been?',
        'How are things going?',
        'Hey, how’s life been?',
        'How’s life treating you lately?',
        'Hey, what’s new in your world?',
        'How’s it going for you?',
        'What’s going on with you?',
        'Hey, what’s been going on?',
        'How’s your week been so far?',
        'Hey, how’s your day been going?',
        'How’s it going for you?',
        'What’s new with you lately?',
        'Hey, how’s your world been?',
        'How’s your life been going?',
        'Hey, how’s your month been?',
        'How’s everything been going for you?',
        'Hey, how’s your year been so far?',
        'How’s your life been going lately?',
        'How’s everything been going lately?',
        'Hey, what’s new in your life?',
        'How have things been with you?',
        'Hey, how’s your time been?',
        'How’s life treating you nowadays?',
        'Hey, how’s everything been going?',
        'How’s your world been treating you?',
        'Hey, how’s your journey been?'
    ];
    const greeting = greetings[Math.floor(Math.random() * greetings.length)];

    await client.sendMessage(M.from, { text: greeting }, { quoted: M });

    const reactionMessage = {
        react: {
            text: reactionEmojis[Math.floor(Math.random() * reactionEmojis.length)],
            key: M.key,
        }
    };
    await client.sendMessage(M.from, reactionMessage, { sendEphemeral: true });
};

module.exports.command = {
    name: 'hi',
    aliases: ['hello', 'hey', 'hola', 'halo', 'bonjour', 'namaste', 'salam', 'wassup', 'sup', 'wassap'],
    category: 'general',
    usage: '| [cmd]',
    exp: 10,
    description: '📚 Greets you with a random message',
};